spring:
  application:
    name: VotingSystem
  profiles:
    active: logs
  datasource:
    url: jdbc:postgresql://localhost:5432/database
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false
